//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserNewsAppService
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsPost
    {
        public int Id { get; set; }
        public string Header { get; set; }
        public string Content { get; set; }
        public int CategoryId { get; set; }
        public int AuthorId { get; set; }
        public string Tags { get; set; }
        public System.DateTime Date { get; set; }
        public string WrittenBy { get; set; }
    }
}
